### ISSUE TITLE
Preserving history

### ISSUE THREAD

**Issue by chowder** [metamorph-inc/omniORB#4]
Hi, I've needed the 4.2.4 version of omniORB so I've simply cloned the repo, updated the relevant bits, and setup the same build on AppVeyor. Thanks a lot for providing this! 

I noticed that you've managed to preserve the history of the omniORB and omniORBpy sources, just curious how you went about doing this as I'd like to do the same on my fork.

**Comment by ksmyth** [comment]
I lost the history of how I cloned the repo, but I believe it was:

```
git svn init -T https://svn.code.sf.net/p/omniorb/svn/branches/4_2  --no-minimize-url
git svn fetch -r 6000:6320
```

You can read more about git-svn here: https://git-scm.com/docs/git-svn
